// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCouDdTCMCETpE7TWx9ZDrkSUzqZM8Qs7I',
    appId: '1:456607336274:web:00684c20f4565f052b9c8b',
    messagingSenderId: '456607336274',
    projectId: 'storeappwayanad',
    authDomain: 'storeappwayanad.firebaseapp.com',
    storageBucket: 'storeappwayanad.appspot.com',
    measurementId: 'G-C2G2YNP3FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcZuCTRnl7aBmsOczwT4c1eQqmcxH8RIE',
    appId: '1:456607336274:android:e096205953cbfb302b9c8b',
    messagingSenderId: '456607336274',
    projectId: 'storeappwayanad',
    storageBucket: 'storeappwayanad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIRkdBbDwAmMXiybEmWBLEazaJMlRtb80',
    appId: '1:456607336274:ios:fa3c30cc641420482b9c8b',
    messagingSenderId: '456607336274',
    projectId: 'storeappwayanad',
    storageBucket: 'storeappwayanad.appspot.com',
    iosClientId: '456607336274-jehcucc57s842t0ae03j2daf7c7cp0ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAppWaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIRkdBbDwAmMXiybEmWBLEazaJMlRtb80',
    appId: '1:456607336274:ios:fa3c30cc641420482b9c8b',
    messagingSenderId: '456607336274',
    projectId: 'storeappwayanad',
    storageBucket: 'storeappwayanad.appspot.com',
    iosClientId: '456607336274-jehcucc57s842t0ae03j2daf7c7cp0ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAppWaya',
  );
}
